server:
  port: 9001
management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: "*"
spring:
  cloud:
    gateway:
      routes:
        - id: todo-service
          uri: http://localhost:7070/
          predicates:
            - Path=/todo/**
          filters:
            - RewritePath=/todo(?<segment>/?.*), $\{segment}
      metrices:
        enabled: true